# Generated by Django 3.0.5 on 2020-04-06 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
