# Generated by Django 3.0.5 on 2020-04-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzers', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quizzers.Category'),
        ),
    ]
