# Generated by Django 3.0.5 on 2020-04-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzers', '0004_club_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='max_players',
            field=models.IntegerField(default=1),
        ),
    ]
