# Generated by Django 3.0.5 on 2020-04-16 00:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzers', '0005_auto_20200412_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.datetime(2020, 4, 16, 0, 23, 21, 322474, tzinfo=utc))),
                ('date_publish', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('name', models.CharField(max_length=100)),
                ('quiz_type', models.CharField(choices=[('mcq', 'MCQ'), ('knockout', 'Knockout'), ('blanks', 'Fill In the Blanks'), ('written', 'written')], max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizzers.Club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quiz_creator', to=settings.AUTH_USER_MODEL)),
                ('quizzers', models.ManyToManyField(related_name='quizzers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Quiz')),
            ],
        ),
    ]
