# Generated by Django 3.0.5 on 2020-04-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200416_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='answer',
            new_name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='correct',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
