# Generated by Django 3.0.5 on 2020-04-12 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 4, 12, 5, 2, 18, 759104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 12, 5, 2, 18, 759959, tzinfo=utc)),
        ),
    ]
