# Generated by Django 3.0.5 on 2020-04-16 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20200416_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
